# .pre-commit-config.yaml
repos: [] # temporarily work around precommit
# repos:
  # ── Ruff: lint + autofix + unused-import cleanup ───────────────────────
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.11.9
  #   hooks:
  #     - id: ruff
  #       args: [--fix]
  #     - id: ruff-format

  # - repo: https://github.com/psf/black
  #   rev: 24.4.2  # Match the version in requirements-dev.txt
  #   hooks:
  #     - id: black
  #       language_version: python3.11

  # ── Isort (import ordering; run *after* Black to keep hashes stable) ───
  # - repo: https://github.com/pre-commit/mirrors-isort
  #   rev: v5.10.1
  #   hooks:
  #     - id: isort
  #       name: isort (python)
  #       args: [--profile=black]
  #       language_version: python3.11

  # ── Mypy (type checking). Non-blocking; use `pass_filenames: false` so
  #    the whole project is checked, not just staged files. ───────────────
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.15.0
  #   hooks:
  #     - id: mypy
  #       args: [app, tests] 
  #       pass_filenames: false
