# /home/dfront/code/dear_future_me/docker-compose.yml
services:
  backend-dev:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8001:80" # Dev API on host port 8001
    volumes:
      - ./app:/code/app
      - ./templates:/code/templates
      - project_data:/data # Shared volume for dev data
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env.dev
    networks:
      - app_network
    profiles:
      - dev

  backend-prod:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:80" # Prod API on host port 8000
    volumes:
      # For prod, consider if code mounting is desired or if the image should be immutable.
      # If immutable, remove ./app and ./templates mounts after ensuring they are COPY'd in Dockerfile.
      - ./app:/code/app
      - ./templates:/code/templates
      - project_data:/data # Or use a separate volume like project_data_prod for isolation
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env.prod
    networks:
      - app_network
    profiles:
      - prod
    # restart: unless-stopped

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8502:8501" # Dev Streamlit on host port 8502
    volumes:
      - ./frontend:/app
      - ./app:/project_app_root/app # For imports from the root 'app' package
      - ./templates:/app/templates # If frontend directly needs templates
    depends_on:
      - backend-dev
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_PORT=8501
      - DFM_API_URL=http://backend-dev:80 # Points to the dev backend service
      - PYTHONPATH=/app:/project_app_root
    command: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0 --server.enableCORS=false --server.enableXsrfProtection=false --logger.level=debug
    env_file:
      - .env.dev
    networks:
      - app_network
    profiles:
      - dev

  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501" # Prod Streamlit on host port 8501
    volumes:
      # For prod, consider if code mounting is desired.
      - ./frontend:/app
      - ./app:/project_app_root/app
      - ./templates:/app/templates
    depends_on:
      - backend-prod
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_PORT=8501
      - DFM_API_URL=http://backend-prod:80 # Points to the prod backend service
      - PYTHONPATH=/app:/project_app_root
    command: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0 --server.enableCORS=false --server.enableXsrfProtection=false --logger.level=info # Prod might use info level
    env_file:
      - .env.prod
    networks:
      - app_network
    profiles:
      - prod
    # restart: unless-stopped

# Define a named volume for persistent data
volumes:
  project_data:
  # You might want separate volumes for prod data if it needs to be isolated, e.g.:
  # project_data_prod:

# Define a default network
networks:
  app_network:
    driver: bridge
