version: '3.8'
services:
  web:
    build: .
    ports: ['8000:8000']
    env_file: .env
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports: ['8001:8000']
    volumes: [chroma_data:/data]
volumes:
  chroma_data: