
services:
  chroma:
    image: ghcr.io/chroma-core/chroma:0.4
    container_name: chroma
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]   # built-in
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - "8001:8000"          # hostPort:containerPort
    volumes:
      - chroma_data:/data
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000

  web:
    build: .
    container_name: dear_future_me
    restart: unless-stopped
    depends_on:
      chroma:
        condition: service_healthy      # wait for vector store
    env_file: .env
    environment:
      - CHROMA_DIR=/data                # 〈── matches processor.py
    volumes:
      - chroma_data:/data               # mount same volume read-only
    ports:
      - "8000:8000"

networks:
  default:
    name: dfm_net

volumes:
  chroma_data:
