# /home/dfront/code/dear_future_me/app/db/migrations/versions/20250518_1824-cfeb3500d51a_add_fields_to_safety_plan_table.py
"""add_fields_to_safety_plan_table

Revision ID: cfeb3500d51a
Revises: dad409e5c747
Create Date: 2025-05-18 18:24:59.006979

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cfeb3500d51a"
down_revision: Union[str, None] = "dad409e5c747"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("SafetyPlanTable", sa.Column("warning_signs", sa.Text(), nullable=True))
    op.add_column("SafetyPlanTable", sa.Column("coping_strategies", sa.Text(), nullable=True))
    op.add_column("SafetyPlanTable", sa.Column("emergency_contacts", sa.Text(), nullable=True))
    op.add_column("SafetyPlanTable", sa.Column("professional_help_contacts", sa.Text(), nullable=True))
    op.add_column("SafetyPlanTable", sa.Column("safe_environment_notes", sa.Text(), nullable=True))
    op.add_column("SafetyPlanTable", sa.Column("reasons_for_living", sa.Text(), nullable=True))
    op.drop_column("SafetyPlanTable", "step_1_warning_signs")
    op.drop_column("SafetyPlanTable", "step_2_internal_coping")
    op.drop_column("SafetyPlanTable", "step_3_social_distractions")
    op.drop_column("SafetyPlanTable", "step_4_help_sources")
    op.drop_column("SafetyPlanTable", "step_5_professional_resources")
    op.drop_column("SafetyPlanTable", "step_6_environment_risk_reduction")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "SafetyPlanTable", sa.Column("step_6_environment_risk_reduction", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "SafetyPlanTable", sa.Column("step_5_professional_resources", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column("SafetyPlanTable", sa.Column("step_4_help_sources", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "SafetyPlanTable", sa.Column("step_3_social_distractions", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column("SafetyPlanTable", sa.Column("step_2_internal_coping", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("SafetyPlanTable", sa.Column("step_1_warning_signs", sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column("SafetyPlanTable", "reasons_for_living")
    op.drop_column("SafetyPlanTable", "safe_environment_notes")
    op.drop_column("SafetyPlanTable", "professional_help_contacts")
    op.drop_column("SafetyPlanTable", "emergency_contacts")
    op.drop_column("SafetyPlanTable", "coping_strategies")
    op.drop_column("SafetyPlanTable", "warning_signs")
    # ### end Alembic commands ###
