"""create_initial_squashed_schema

Revision ID: dad409e5c747
Revises:
Create Date: 2025-05-18 12:37:34.035122

"""

from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dad409e5c747"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "UserTable",
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_UserTable_email"), "UserTable", ["email"], unique=True)
    op.create_table(
        "SafetyPlanTable",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("step_1_warning_signs", sa.Text(), nullable=True),
        sa.Column("step_2_internal_coping", sa.Text(), nullable=True),
        sa.Column("step_3_social_distractions", sa.Text(), nullable=True),
        sa.Column("step_4_help_sources", sa.Text(), nullable=True),
        sa.Column("step_5_professional_resources", sa.Text(), nullable=True),
        sa.Column("step_6_environment_risk_reduction", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["UserTable.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "UserProfileTable",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("future_me_persona_summary", sa.Text(), nullable=True),
        sa.Column("gender_identity_pronouns", sa.String(length=100), nullable=True),
        sa.Column("therapeutic_setting", sa.String(length=255), nullable=True),
        sa.Column("therapy_start_date", sa.Date(), nullable=True),
        sa.Column("dfm_use_integration_status", sa.String(length=50), nullable=True),
        sa.Column("primary_emotional_themes", sa.Text(), nullable=True),
        sa.Column("recent_triggers_events", sa.Text(), nullable=True),
        sa.Column("emotion_regulation_strengths", sa.Text(), nullable=True),
        sa.Column("identified_values", sa.Text(), nullable=True),
        sa.Column("self_reported_goals", sa.Text(), nullable=True),
        sa.Column("therapist_language_to_mirror", sa.Text(), nullable=True),
        sa.Column("user_emotional_tone_preference", sa.String(length=100), nullable=True),
        sa.Column("tone_alignment", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["UserTable.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("UserProfileTable")
    op.drop_table("SafetyPlanTable")
    op.drop_index(op.f("ix_UserTable_email"), table_name="UserTable")
    op.drop_table("UserTable")
    # ### end Alembic commands ###
