"""add user profile table

Revision ID: e5f9fba9d91b
Revises:
Create Date: 2024-07-29 12:00:00.000000

"""

from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5f9fba9d91b"
down_revision: Union[str, None] = None  # Assuming this is the first migration or replace with actual previous revision
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "UserTable",
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_UserTable_email"), "UserTable", ["email"], unique=True)
    op.create_table(
        "UserProfileTable",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("future_me_persona_summary", sa.Text(), nullable=True),
        sa.Column("gender_identity_pronouns", sa.String(length=100), nullable=True),
        sa.Column("therapeutic_setting", sa.String(length=255), nullable=True),
        sa.Column("therapy_start_date", sa.Date(), nullable=True),
        sa.Column("dfm_use_integration_status", sa.String(length=50), nullable=True),
        sa.Column("primary_emotional_themes", sa.Text(), nullable=True),
        sa.Column("recent_triggers_events", sa.Text(), nullable=True),
        sa.Column("emotion_regulation_strengths", sa.Text(), nullable=True),
        sa.Column("identified_values", sa.Text(), nullable=True),
        sa.Column("self_reported_goals", sa.Text(), nullable=True),
        sa.Column("therapist_language_to_mirror", sa.Text(), nullable=True),
        sa.Column("user_emotional_tone_preference", sa.String(length=100), nullable=True),
        sa.Column("tone_alignment", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["UserTable.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("UserProfileTable")
    op.drop_index(op.f("ix_UserTable_email"), table_name="UserTable")
    op.drop_table("UserTable")
    # ### end Alembic commands ###
